docs/README.md

fix: contributor docs

---

packages/core-sdk/src/index.ts
scripts/explore-offer.ts

chore: add reservedRange in explore-offer script

---

e2e/meta-tx-gateway/src/services/meta-tx.ts
e2e/tests/meta-tx.test.ts
packages/common/src/abis/BiconomyForwarderABI.json
packages/common/src/abis/index.ts
packages/common/src/configs.ts
packages/common/src/types/configs.ts
packages/common/src/utils/validation.ts
packages/core-sdk/src/forwarder/biconomy-interface.ts
packages/core-sdk/src/forwarder/handler.ts
packages/core-sdk/src/forwarder/index.ts
packages/core-sdk/src/forwarder/mock-interface.ts
packages/core-sdk/src/index.ts
packages/core-sdk/src/meta-tx/biconomy.ts
packages/core-sdk/src/meta-tx/handler.ts
packages/core-sdk/src/meta-tx/mixin.ts
packages/core-sdk/src/native-meta-tx/handler.ts
packages/core-sdk/src/native-meta-tx/mixin.ts
packages/core-sdk/src/utils/signature.ts
packages/core-sdk/src/voucher/handler.ts
packages/core-sdk/src/voucher/interface.ts
packages/core-sdk/src/voucher/mixin.ts
packages/subgraph/package.json

feat: support Biconomy meta tx with Trusted Forwarder

---

packages/subgraph/package.json

Reverts bosonprotocol/core-components#443

Revert "ci: fix deploy subgraph pipeline"

---

contracts/accounts.js
e2e/docker-compose.yml
e2e/tests/core-sdk-extend-offer.test.ts
e2e/tests/core-sdk-premint.test.ts
e2e/tests/meta-tx.test.ts
e2e/tests/utils.ts
packages/core-sdk/src/meta-tx/handler.ts
packages/core-sdk/src/meta-tx/mixin.ts
packages/core-sdk/src/metadata/base.graphql
packages/core-sdk/src/offers/handler.ts
packages/core-sdk/src/offers/mixin.ts
packages/core-sdk/src/offers/queries.graphql
packages/core-sdk/src/offers/renderContractualAgreement.ts
packages/core-sdk/src/subgraph.ts
packages/subgraph/schema.graphql
packages/subgraph/src/mappings/offer-handler.ts
packages/subgraph/subgraph.template.yaml

- add offer range data in subgraph
- add OfferExtended event handler in subgraph
- add extendOffer/extendOfferBatch methods
- new e2e tests have been added

feat: add offer range in subgraph

---

packages/core-sdk/src/seaport/handler.ts
packages/subgraph/subgraph.template.yaml

- fix a problem with subgraph
- fix a value missing in seaport structure
- the subgraph is correctly deployed and working on a test project (manual)

fix: subgraph 2.2.0

---

.github/workflows/ci.yaml
e2e/jest.config.js

- Generate code coverage report when running e2e tests (with appropriate configuration)
- Push e2e code coverage report to be merged in codecov.io
N/A

chore: improve test coverage

---

e2e/docker-compose.yml
e2e/run-e2e-services.sh
e2e/tests/core-sdk-premint.test.ts
packages/common/src/abis/IBosonVoucher.json
packages/core-sdk/src/subgraph.ts
packages/subgraph/schema.graphql
packages/subgraph/src/mappings/boson-voucher.ts
packages/subgraph/src/mappings/offer-handler.ts
packages/subgraph/subgraph.template.yaml

protocol version set to:
```
commit f7098fe885c99c87c23a77113af3921ec2e3293e (HEAD, origin/main, origin/HEAD)
Merge: d9aa5af9 bf6a7b0e
Author: Mischa <mischa@mmt.me.uk>
Date:   Fri Apr 21 16:56:56 2023 +0100
Merge pull request #541 from bosonprotocol/slither-action
Add Slither Analyzer to Github Actions
```

feat: add minted field in offer.range and update offer.quantityAvailable on reserving a range

---

e2e/jest.config.js

chore: fix e2e tests code coverage config

---

e2e/tests/utils.ts
packages/core-sdk/src/accounts/queries.graphql
packages/core-sdk/src/subgraph.ts
packages/metadata/src/seller/index.ts
packages/metadata/src/seller/schema.json
packages/subgraph/schema.graphql
packages/subgraph/src/entities/metadata/seller/index.ts
packages/subgraph/tests/metadata/seller.json

This reverts commit 175b47e72315732b9020ab39ea88c66428d74ec5.

chore: revert commit that removed seller metadata kind field

---

packages/core-sdk/src/meta-tx/mixin.ts
packages/subgraph/scripts/render-manifest.ts

chore: update the subgraph starting block for staging env

---

.github/workflows/ci.yaml
.gitmodules
contracts/.dockerignore
contracts/.gitignore
contracts/package-lock.json
contracts/package.json
contracts/scripts/postinstall.js
e2e/docker-compose.yml
e2e/run-e2e-services.cmd
e2e/run-e2e-services.sh
e2e/run-e2e-suite.cmd
e2e/run-e2e-suite.sh

chore: remove boson-protocol-contracts submodule

---

e2e/tests/accounts.test.ts
packages/core-sdk/src/subgraph.ts
packages/subgraph/schema.graphql
packages/subgraph/src/entities/metadata/seller/salesChannels.ts
packages/subgraph/src/utils/json.ts
packages/subgraph/tests/account-handler.test.ts
packages/subgraph/tests/metadata/seller.json

fix: convert SalesChannelDeployment.lastUpdated from number into BigInt

---

packages/react-kit/src/components/modal/components/Redeem/ExchangeView/detail/DetailOpenSea.tsx
packages/react-kit/src/lib/utils/exchange.ts

fixes https://github.com/bosonprotocol/widgets/issues/5

fix: redemption widget - opensea link is not correct

---

package-lock.json
packages/react-kit/package.json

fixes https://github.com/bosonprotocol/widgets/issues/20
react-kit / storybook

fix: upgrade chat-sdk version in react-kit

---

packages/react-kit/src/components/buttons/Button.tsx
packages/react-kit/src/components/chat/InitializeChat.tsx
packages/react-kit/src/components/ui/ThemedButton.tsx
packages/react-kit/src/stories/ui/ThemedButton.stories.tsx

refering to https://github.com/bosonprotocol/widgets/issues/28

fix: redemption widget: change initialise button colour

---

packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
packages/react-kit/src/components/widgets/redemption/RedemptionWidget.tsx

relates to https://github.com/bosonprotocol/widgets/issues/6
react-kit / storybook

feat: link "raise dispute" button to dr center according to env

---

packages/react-kit/src/components/exchangePolicy/ExchangePolicyDetails.tsx
packages/react-kit/src/components/modal/NonModal.tsx
packages/react-kit/src/components/modal/components/Redeem/Confirmation/ConfirmationView.tsx
packages/react-kit/src/components/modal/components/Redeem/ContractualAgreementView/ContractualAgreementView.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangePolicy/ExchangePolicy.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/ExchangeFullDescriptionView/ExchangeFullDescriptionView.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/ExchangeView.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/RedeemSuccess.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/cancellation/CancellationView.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/expireVoucher/ExpireVoucherView.tsx
packages/react-kit/src/components/modal/components/Redeem/LicenseAgreementView/LicenseAgreementView.tsx
packages/react-kit/src/components/modal/components/Redeem/MyItems/MyItems.tsx
packages/react-kit/src/components/modal/components/Redeem/RedeemForm/RedeemFormView.tsx
packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
packages/react-kit/src/components/modal/components/Redeem/StepsOverview/PurchaseOverviewView.tsx
packages/react-kit/src/components/modal/components/Redeem/StepsOverview/StepsOverview.tsx
packages/react-kit/src/components/ui/ThemedButton.tsx
packages/react-kit/src/components/widgets/finance/Finance.tsx
packages/react-kit/src/components/widgets/redemption/RedemptionWidget.tsx
packages/react-kit/src/stories/widgets/Redemption.stories.tsx

relates to https://github.com/bosonprotocol/widgets/issues/34

feat: redemption widget - allow to hide modal

---

.github/workflows/pin-to-pinata.yaml
scripts/pin-to-pinata.ts

last minutes changes to prepare Metavsere Art Week
N/A

chore: merge from releases/mvaw 2023

---

packages/react-kit/src/theme.ts

fix: change secondary colour to map dapp colour scheme

---

data/exchangePolicies/exchangePolicyRules.template.json
data/ipfs.txt

chore: upgrade fair exchange policy rules with new agreement hash

---

packages/react-kit/src/components/modal/components/Redeem/ExchangeView/detail/DetailOpenSea.tsx

refer to  
https://github.com/bosonprotocol/interface/issues/819

fix: adapt opensea link wrt chain used in the env

---

README.md

Updates the README file with links to our bug bounty
Check the README file :)

chore: updates discord and bug bounty links

---

.github/workflows/deploy-staging-subgraph.yaml
packages/common/src/configs.ts
packages/common/src/types/configs.ts
packages/subgraph/package.json
packages/subgraph/scripts/render-manifest.ts

chore: create config for staging configuration on goerli

---

contracts/Dockerfile
docs/guides/use-with-ethers-ipfs.md
e2e/docker-compose.yml
e2e/tests/accounts.test.ts

chore: docs update and add a new test

---

packages/subgraph/src/entities/metadata/product-v1/product.ts

fix: ensure identification of ProductV1ProductOverrides is correct

---

packages/common/src/mappings.ts
packages/core-sdk/src/offers/queries.graphql
packages/core-sdk/src/subgraph.ts
scripts/pin-to-pinata.ts

fix: ensure pin-to-pinata is working on production

---

.github/workflows/deploy-prod-subgraph.yaml
.github/workflows/pin-to-pinata.yaml
packages/common/src/mappings.ts
packages/subgraph/package.json
packages/subgraph/scripts/render-manifest.ts

chore: prepare for production/Ethereum deployment

---

packages/react-kit/src/components/environment/EnvironmentContext.ts
packages/react-kit/src/components/environment/EnvironmentProvider.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/ExchangeView.tsx
packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
packages/react-kit/src/components/widgets/finance/FinanceWidget.tsx
packages/react-kit/src/components/widgets/finance/convertion-rate/ConvertionRateProvider.tsx
packages/react-kit/src/components/widgets/redemption/RedemptionWidget.tsx
packages/react-kit/src/hooks/useCoreSdkWithContext.ts
packages/react-kit/src/stories/widgets/Finance.stories.tsx
packages/react-kit/src/stories/widgets/Redemption.stories.tsx

refers to https://github.com/bosonprotocol/widgets/issues/64
storybook

fix: adapt widget config

---

packages/react-kit/src/components/modal/components/Redeem/ByassModeProvider/ByassModeProvider.tsx
packages/react-kit/src/components/modal/components/Redeem/ByassModeProvider/const.ts
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/cancellation/CancelExchange.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/cancellation/CancellationView.tsx
packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
packages/react-kit/src/components/widgets/index.tsx
packages/react-kit/src/stories/widgets/Redemption.stories.tsx

fixes https://github.com/bosonprotocol/interface/issues/817

feat: display sucess message after cancelling exchange

---

packages/common/src/mappings.ts
packages/react-kit/src/components/form/CountrySelect.tsx
packages/react-kit/src/components/modal/components/Redeem/Confirmation/Confirmation.tsx
packages/react-kit/src/components/modal/components/Redeem/Confirmation/ConfirmationView.tsx
packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
packages/react-kit/src/components/widgets/redemption/RedemptionWidget.tsx
packages/react-kit/src/components/widgets/redemption/provider/RedemptionContext.tsx
packages/react-kit/src/components/widgets/redemption/provider/RedemptionProvider.tsx
packages/react-kit/src/hooks/callbacks/useRedemptionCallbacks.ts
packages/react-kit/src/stories/widgets/Redemption.stories.tsx

feat: redemption widget - manage callbacks

---

packages/react-kit/src/components/modal/components/SellerFinance/FinanceDeposit.tsx
packages/react-kit/src/components/modal/components/SellerFinance/FinanceWithdraw.tsx
packages/react-kit/src/hooks/connection/connection.ts
packages/react-kit/src/hooks/offer/useExchangeTokenBalance.ts

fixes: https://github.com/bosonprotocol/core-components/issues/618

feat: update financedeposit and financewithdraw components with new useerc20balance instead of wagmis usebalance

---

packages/react-kit/src/components/chat/ChatProvider/ChatProvider.tsx
packages/react-kit/src/components/modal/components/Redeem/Confirmation/ConfirmationView.tsx
packages/react-kit/src/components/modal/components/Redeem/ExchangeView/DetailView/TokenGated.tsx
packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
packages/react-kit/src/components/modal/nonModal/Header.tsx
packages/react-kit/src/components/modal/nonModal/NonModal.tsx
packages/react-kit/src/components/signer/SignerContext.tsx
packages/react-kit/src/components/widgets/finance/FinanceWidget.tsx
packages/react-kit/src/components/widgets/redemption/RedemptionWidget.tsx
packages/react-kit/src/hooks/connection/connection.ts
packages/react-kit/src/hooks/useCoreSdkOverrides.ts
packages/react-kit/src/hooks/useCoreSdkWithContext.ts
packages/react-kit/src/lib/errors/transactions.ts
packages/react-kit/src/lib/signer/externalSigner.ts
packages/react-kit/src/lib/signer/useCallSignerFromIframe.ts

related to https://github.com/bosonprotocol/widgets/pull/101 and https://github.com/bosonprotocol/interface/pull/966

feat: redemption widget without connecting wallet

---

packages/core-sdk/src/funds/handler.ts
packages/core-sdk/src/funds/interface.ts
packages/core-sdk/src/funds/mixin.ts
packages/core-sdk/tests/funds/handler.test.ts

fixes: https://github.com/bosonprotocol/core-components/issues/615

refactor: rename sellerId to entityId in withdrawFunds and withdrawAllAvailableFunds functions

---

e2e/tests/core-sdk-collections.test.ts
e2e/tests/meta-tx.test.ts
e2e/tests/utils.ts
packages/core-sdk/src/accounts/handler.ts
packages/core-sdk/src/accounts/mixin.ts
packages/core-sdk/src/meta-tx/handler.ts
packages/core-sdk/src/offers/storage.ts
packages/core-sdk/src/orchestration/handler.ts
packages/ipfs-storage/src/ipfs/metadata.ts
packages/ipfs-storage/tests/ipfs.test.ts
packages/metadata/src/collection/index.ts
packages/metadata/src/collection/schema.json
packages/metadata/src/index.ts
packages/react-kit/src/hooks/lens/useGetLensProfiles.ts
packages/react-kit/src/hooks/useCoreSdkOverrides.ts
packages/react-kit/src/lib/lens/fetchLens.ts
packages/react-kit/src/stories/widgets/Redemption.stories.tsx
scripts/explore-offer.ts

fixes https://github.com/bosonprotocol/widgets/issues/98
N/A

fix: avoid crashing when lens profile can't be fetched

---

contracts/accounts.js
e2e/docker-compose.yml
e2e/tests/core-sdk-accounts.test.ts
e2e/tests/utils.ts
package.json
packages/core-sdk/src/accounts/mixin.ts
packages/core-sdk/src/accounts/queries.graphql
packages/core-sdk/src/accounts/subgraph.ts
packages/core-sdk/src/subgraph.ts
packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
packages/react-kit/src/hooks/useCurrentSellers.ts
scripts/get-seller.ts

fixes #641 
`npm run get-seller 0xc6295603d03c8E8CaDB2c3105A527B44010a4DF4`
--> should return seller Id:31, although the wallet 0xc6295603d03c8E8CaDB2c3105A527B44010a4DF4 is not listed as a role for any seller
+ added e2e test

fix: change getSellerByAddress in case the seller owns a LENS token

---

packages/react-kit/src/hooks/index.ts
packages/react-kit/src/hooks/useHandleText.ts
packages/react-kit/src/lib/dates/checkIfTimestampIsToo.ts

(another PR on the interface will follow)

feat: make useHandleText support offers that do not expire

---

.gitignore
package-lock.json
package.json

run ```npm run ts-coverage``` and a new folder called coverage-ts will be created with a report in html

chore: add ts-coverage script

---

packages/common/src/abis/ERC1155.json
packages/core-sdk/src/erc1155/handler.ts
packages/core-sdk/src/erc1155/mixin.ts
packages/core-sdk/src/erc721/handler.ts
packages/core-sdk/src/erc721/mixin.ts
packages/react-kit/src/components/modal/components/common/OfferFullDescription/GeneralProductData.tsx
packages/react-kit/src/components/modal/components/common/detail/SlickSlider.tsx
packages/react-kit/src/components/modal/components/common/detail/TokenGatedItem.tsx
packages/react-kit/src/components/modal/components/common/detail/useGetOfferDetailData.tsx
packages/react-kit/src/components/offerPolicy/OfferPolicyDetails.tsx
packages/react-kit/src/hooks/contracts.ts
packages/react-kit/src/stories/widgets/Commit.stories.tsx

fixes: https://github.com/bosonprotocol/core-components/issues/653

fix: some commit widget issues

---

packages/react-kit/src/hooks/useSellers.ts

relates to https://github.com/bosonprotocol/interface/issues/1003

fix: ensure useSellers refresh when seller curation list is fetched

---

packages/react-kit/src/components/modal/components/Commit/CommitNonModal.tsx
packages/react-kit/src/components/widgets/commit/CommitWidget.tsx

fix: commit widget is not loading

---

packages/react-kit/src/components/config/ConfigContext.ts
packages/react-kit/src/components/config/ConfigProvider.tsx
packages/react-kit/src/components/modal/components/Commit/DetailView/ExternalCommitDetailView.tsx
packages/react-kit/src/components/widgets/commit/CommitWidget.tsx
packages/react-kit/src/components/widgets/commit/CommitWidgetProviders.tsx
packages/react-kit/src/hooks/index.ts
packages/react-kit/src/hooks/uniswap/useIsWindowVisible.ts
packages/react-kit/src/state/hooks.ts
packages/react-kit/src/state/lists/updater.ts
packages/react-kit/src/state/reducer.ts
packages/react-kit/src/state/reduxContext.ts
packages/react-kit/src/state/updaters.tsx

also exports useIsWindowVisible 
needed in: https://github.com/bosonprotocol/interface/pull/1036

fix: unexpected blank page after committing to a product

---

.github/workflows/pin-to-pinata.yaml

fix: fix pin-to-pinata GH action

---

scripts/abi-signatures.ts

chore: add protocol errors in generated abi-signatures.csv

---

packages/react-kit/src/components/ui/MuteButton.tsx
packages/react-kit/src/components/ui/Video.tsx
packages/react-kit/src/index.tsx

feat: add mute button to videos

---

.github/workflows/pin-to-pinata.yaml

chore: remove sepolia-staging env from pin-to-pinata job

---

packages/react-kit/src/components/cta/offer/CommitButton.tsx
packages/react-kit/src/components/modal/components/common/StepsOverview/PurchaseOverview.tsx

fixes: https://github.com/bosonprotocol/core-components/issues/695

chore: change copies commit to commit to buy

---

packages/core-sdk/src/utils/tokenInfoManager.ts

fix: render Contractual Agreement fails on Sepolia network

---

packages/core-sdk/src/errors/mixin.ts
packages/core-sdk/tests/errors/decodeErrors.test.ts
packages/react-kit/src/components/widgets/finance/FinanceWidget.tsx
packages/react-kit/src/components/widgets/finance/FinanceWidgetProviders.tsx
packages/react-kit/src/hooks/useCtaClickHandler.ts
packages/react-kit/src/hooks/useCurrentSellers.ts
packages/react-kit/src/stories/widgets/Finance.stories.tsx

fix https://github.com/bosonprotocol/widgets/issues/136

fix: finance widget is not loading

---

packages/react-kit/src/components/modal/components/SellerFinance/FinanceDeposit.tsx
packages/react-kit/src/components/modal/components/SellerFinance/FinanceWithdraw.tsx
packages/react-kit/src/lib/numbers/numbers.ts

fix: rounded values may be wrong

---

packages/common/src/configs.ts

fix: sepolia testing protocol contract change

---

packages/react-kit/src/components/scroll/ScrollToID.tsx
packages/react-kit/src/components/scroll/ScrollToTop.tsx
packages/react-kit/src/hooks/index.ts
packages/react-kit/src/index.tsx

chore: export some existing components and hooks

---

packages/react-kit/src/components/form/BaseInput.tsx
packages/react-kit/src/components/form/BaseTagsInput.tsx
packages/react-kit/src/components/form/BaseTextArea.tsx
packages/react-kit/src/components/form/Checkbox.tsx
packages/react-kit/src/components/form/CountrySelect.tsx
packages/react-kit/src/components/form/Datepicker.tsx
packages/react-kit/src/components/form/InputColor.tsx
packages/react-kit/src/components/form/Phone.tsx
packages/react-kit/src/components/form/Select.tsx
packages/react-kit/src/components/form/Upload/Upload.tsx
packages/react-kit/src/components/form/index.ts
packages/react-kit/src/index.tsx
packages/react-kit/src/stories/selects/CountrySelect.stories.tsx

feat: export country select

---

packages/core-sdk/src/marketplaces/opensea.ts

chore: adapt marketplace to avoid compilation issue on Fermion

---

packages/react-kit/src/components/buttons/BaseButton.tsx
packages/react-kit/src/components/form/Select.tsx
packages/react-kit/src/components/form/index.ts
packages/react-kit/src/components/form/types.ts
packages/react-kit/src/stories/selects/Select.stories.tsx

feat: make select component generic via a theme prop

---

packages/react-kit/src/components/form/BaseCheckbox.tsx
packages/react-kit/src/components/form/Checkbox.tsx
packages/react-kit/src/components/form/Field.styles.ts
packages/react-kit/src/components/form/Upload/WithUploadToIpfs.tsx
packages/react-kit/src/components/form/index.ts
packages/react-kit/src/components/form/types.ts
packages/react-kit/src/components/ui/IpfsImage.tsx
packages/react-kit/src/components/ui/Video.tsx
packages/react-kit/src/index.tsx
packages/react-kit/src/stories/buttons/Upload.stories.tsx
packages/react-kit/src/stories/form/BaseCheckbox.stories.tsx

+ Upload with video case in storybook
+ checkbox in storybook

feat: make checkbox generic

---

packages/react-kit/src/lib/const/chainInfo.ts

add Local network in the chain info, so that it would be possible to connect the Local env from the Fermion UI
closes #776 
N/A

fix: add Local chain in chain info

---

packages/react-kit/src/components/buttons/CommitButtonView.tsx

https://boson-protocol.slack.com/archives/C05ME69EWKU/p1721317904756039

style: make commit button narrower

---

e2e/tests/core-sdk.test.ts
packages/core-sdk/src/exchanges/queries.graphql
packages/core-sdk/src/subgraph.ts
packages/subgraph/schema.graphql
packages/subgraph/src/mappings/funds-handler.ts
packages/subgraph/subgraph.template.yaml

feat: add protocolFee events in subgraph

---

.github/workflows/ci.yaml
e2e/run-e2e-services.cmd
e2e/run-e2e-services.sh
e2e/run-e2e-suite.cmd
e2e/run-e2e-suite.sh

same as https://github.com/fermionprotocol/core-components/issues/81 for Boson

chore: migrate to docker compose v2

---

packages/common/src/types/web3-lib-adapter.ts
packages/common/tests/mocks.ts
packages/eth-connect-sdk/src/eth-connect-adapter.ts
packages/ethers-sdk/src/ethers-adapter.ts
packages/react-kit/src/lib/signer/externalSigner.ts

feat: add estimateGas in Web3LibAdapter

---

packages/react-kit/src/components/productCard/commonStyles.ts
packages/react-kit/src/components/skeleton/ProductCardSkeleton.tsx

fix: remove min height, products skeleton changes

---

packages/react-kit/src/components/currencyDisplay/CurrencyDisplay.tsx
packages/react-kit/src/components/exchangeCard/ExchangeCard.tsx
packages/react-kit/src/components/modal/components/Redeem/MyItems/Exchange.tsx
packages/react-kit/src/components/productCard/ProductCard.tsx
packages/react-kit/src/components/productCard/commonStyles.ts
packages/react-kit/src/components/skeleton/CollectionsCardSkeleton.tsx
packages/react-kit/src/components/skeleton/ProductCardSkeleton.tsx

feat: fix collection skeleton

---

packages/react-kit/src/lib/config/config.ts

fix: remove check if magicLinkKey is defined in configuration

---

packages/react-kit/src/components/buttons/BaseButton.tsx
packages/react-kit/src/components/form/Upload/BaseUpload.tsx
packages/react-kit/src/components/ui/Video.tsx
packages/react-kit/src/components/wallet2/accountDrawer/IconButton.tsx
packages/react-kit/src/stories/buttons/Upload.stories.tsx
packages/react-kit/src/types/helpers.ts

also fixed some transient props that were passed with no $ prefix
- if there is a placeholder, then it is not shown if the preview is visible
- video upload stories fixed, the uploaded video was not visible
- added missing class to videoWrapper while loading so it can be styled from outside

fix: video upload component

---

.github/workflows/deploy-staging-subgraph.yaml
.github/workflows/publish-alpha.yaml

ci: try to fix pipeline

---

.github/workflows/deploy-staging-subgraph.yaml
.github/workflows/deploy-testing-subgraph.yaml

ci: fix git pull is not added in the correct workflow

---

.github/workflows/deploy-testing-subgraph.yaml
.github/workflows/publish-alpha.yaml

ci: fix GITHUB_TOKEN secret used to push changes

---

.github/workflows/deploy-testing-subgraph.yaml

ci: try to fix git push issue

---

.github/workflows/deploy-staging-subgraph.yaml
.github/workflows/deploy-testing-subgraph.yaml
.github/workflows/publish-alpha.yaml

ci: try to fix git push changes

---

packages/subgraph/README.md

chore: force change in subgraph workspace

---

packages/subgraph/src/utils/json.ts

chore: dummy change in subgraph workspace

---

packages/react-kit/src/components/form/Field.styles.ts
packages/react-kit/src/components/form/Upload/BaseUpload.tsx
packages/react-kit/src/components/form/Upload/UploadedSinglePdfFile.tsx
packages/react-kit/src/components/form/index.ts
packages/react-kit/src/stories/buttons/Upload.stories.tsx

this is to make the upload button look like the ones we have in boson which have sharp edges

style: remove border radius pdf upload

---

packages/common/src/configs.ts

feat: replace Biconomy with internal metaTx gateway

---

packages/react-kit/src/components/form/Field.styles.ts
packages/react-kit/src/components/form/Upload/BaseUpload.tsx
packages/react-kit/src/components/form/Upload/UploadedFile.tsx
packages/react-kit/src/components/form/Upload/UploadedFiles.tsx
packages/react-kit/src/components/form/Upload/UploadedSinglePdfFile.tsx

Implement new design for multi pdf upload, in previous branches related to upload we didn't know how it should look like

feat: enhance multi pdf file upload

---

packages/react-kit/src/lib/const/tokens.ts

fix: missing Base Sepolia WETH token definition

---

package.json
packages/core-sdk/src/marketplaces/opensea.ts
packages/core-sdk/src/marketplaces/types.ts
packages/core-sdk/tests/marketplaces/opensea.test.ts
scripts/opensea/cancel-order.ts

related to https://github.com/fermionprotocol/core-components/issues/209 and https://github.com/fermionprotocol/core-components/issues/210

feat: add cancelOrder method on Opensea

---

packages/common/src/configs.ts
packages/common/src/mappings.ts

- fix BOSON PriceDiscovery contract address on BASE
- add BOSON Token contract address on BASE
- add USDC Token on BASE and SEPOLIA BASE (required for FERMION)

chore: complete the configuration for production base network

---

packages/common/src/mappings.ts

fix: incorrect Base USDC address

---

e2e/docker-compose.yml
package-lock.json
packages/common/.gitignore
packages/react-kit/package.json
scripts/update-protocol-addresses.ts

Small fixes and changes, some of them required to get dApp and widgets working on Optimism chain (upgrade @uniswap/sdk-core version to get up-to-date optimism chain data)
N/A

chore: fix script update-protocol-addresses

---

package-lock.json
packages/react-kit/package.json

chore: upgrade roblox-sdk

---

packages/react-kit/src/index.tsx

chore: export DetailOpenSea component

---

packages/react-kit/src/components/modal/components/common/DetailOpenSea.tsx
packages/react-kit/src/lib/utils/exchange.ts

chore: change exchange type used by DetailOpenSea

---

packages/common/src/configs.ts
packages/common/src/index.ts
packages/common/src/types/configs.ts
packages/core-sdk/src/index.ts

also create getConfigFromConfigId

feat: improve types protocolConfig

---

packages/ipfs-storage/src/ipfs/base.ts
packages/ipfs-storage/tests/ipfs.test.ts

Updated Case Coverage Summary
✅ IPFS URIs - All handled correctly:
ipfs://QmValidCid → getByCID
ipfs://QmValidCid/path → getByCID
ipfs://invalidcid → throws error (doesn't reach getByURL)
✅ Raw CIDs - All handled correctly:
QmValidCid → getByCID
QmValidCid/path/to/file → getByCID
invalidhash123 → throws error (doesn't reach getByURL)
✅ URLs with protocols - All go to getByURL (let fetch handle validation):
http://example.com → getByURL
https://example.com/path → getByURL
ftp://example.com/file.txt → getByURL → fetch will throw "unsupported protocol" error
file:///path/to/file → getByURL → fetch will throw appropriate error
data:text/plain;base64,SGVsbG8= → getByURL → fetch will handle appropriately
✅ Invalid inputs:
"" → throws error
Non-string → throws error

feat: cover more cases ipfs storage get

---

contracts/package.json
contracts/scripts/postinstall.js

chore: override contracts version in protocol container
