packages/core-sdk/src/meta-tx/handler.ts
This change is required to get core-sdk loading in the DCL scene. Regression was introduced 3 weeks ago, making the core-sdk versions unable to work with DCL
N/A
=> fix: dcl loading issue

packages/core-sdk/src/forwarder/handler.ts, packages/core-sdk/src/meta-tx/biconomy.ts, packages/core-sdk/src/meta-tx/handler.ts, packages/core-sdk/src/meta-tx/mixin.ts, packages/core-sdk/src/voucher/handler.ts, packages/core-sdk/src/voucher/interface.ts
- following the issue with Biconomy forwarder, the coreSDK now gets the Biconomy config (via HTTP API) to list all forwarder addresses, then check the voucher contract which one it supports. If none is found, an exception is raised.
- Once the forwarder to use has been identified, the meta-tranasaction is built and signed (with the appropriate forwarder address), then relayed through Biconomy
N/A - e2e tests only use local forwarder and relayer
=> feat: adapt biconomy relaying with forwarder

package.json, scripts/create-offer-batch.ts
=> chore: add create-offer-batch script

.github/workflows/pin-to-pinata.yaml
=> chore: allow to run pin-to-pinata workflow manually on a branch

packages/core-sdk/package.json, packages/core-sdk/src/native-meta-tx/handler.ts
USDC approval meta-tx signing fails only when called from DCL
This was coming from getNonce() implementation that retries with "nonces" instead of "getNonce" only when failing and the error message matches the one returned by Metamask. However on DCL, we are using an HTTP provider instead of Metamask and the error message is not the same.
N/A
=> fix: usdc approve fails from dcl

e2e/tests/accounts.test.ts, e2e/tests/utils.ts, packages/core-sdk/src/subgraph.ts, packages/metadata/src/seller/schema.json, packages/subgraph/schema.graphql, packages/subgraph/src/entities/metadata/seller/index.ts, packages/subgraph/src/entities/metadata/seller/media.ts, packages/subgraph/tests/metadata/seller.json
the image type of the seller metadata was set to IMAGE instead of the real image type: image/jpeg, image/png... that was saved in the metadata (although in the tests we were saving IMAGE too)
=> fix: seller metadata images type

data/exchangePolicies/exchangePolicyRules.template.json, data/exchangePolicies/fairExchangePolicy-testing.json, data/ipfs.txt, e2e/tests/core-sdk-extend-offer.test.ts, e2e/tests/productV1.test.ts, package.json, packages/core-sdk/package.json, packages/core-sdk/src/offers/checkExchangePolicy.ts, packages/core-sdk/src/offers/index.ts, packages/core-sdk/src/offers/mixin.ts, packages/core-sdk/tests/check-exchange-policy.test.ts, packages/core-sdk/tests/exchangePolicy/examples/invalidOffer1.json, packages/core-sdk/tests/exchangePolicy/examples/invalidOffer2.json, packages/core-sdk/tests/exchangePolicy/examples/invalidOffer3.json, packages/core-sdk/tests/exchangePolicy/examples/invalidOffer4.json, packages/core-sdk/tests/exchangePolicy/examples/invalidOffer5.json, packages/core-sdk/tests/exchangePolicy/examples/validOffer.json, packages/core-sdk/tests/exchangePolicy/exchangePolicyRules.local.json, packages/core-sdk/tests/exchangePolicy/exchangePolicyRules.production.json, packages/core-sdk/tests/exchangePolicy/exchangePolicyRules.staging.json, packages/core-sdk/tests/exchangePolicy/exchangePolicyRules.testing.json, scripts/checkOfferExchangePolicy.ts
a new service is now available in the core-sdk:
`public async checkExchangePolicy(
offerId: BigNumberish,
rules: offers.CheckExchangePolicyRules
): Promise<offers.CheckExchangePolicyResult>`
Example of the rules are available here (env dependent):
[exchangePolicyRules.testing.json](packages\core-sdk\tests\exchangePolicy\exchangePolicyRules.testing.json)
[exchangePolicyRules.staging.json](packages\core-sdk\tests\exchangePolicy\exchangePolicyRules.staging.json)
[exchangePolicyRules.production.json](packages\core-sdk\tests\exchangePolicy\exchangePolicyRules.production.json)
- unit tests have been added in core-sdk package
- a script has been added to call the service manually
=> feat: allow checking an offer is compliant with the fair exchange policy

packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
- fix: reallow the user to connect wallet in redemption widget
- feat: reinitialize the redeem wizard when switching wallet (https://github.com/bosonprotocol/widgets/issues/18)
react-build / storybook
=> feat: reinitialize the redeem modal steps when switching wallet

packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx
relates to https://github.com/bosonprotocol/widgets/issues/14
=> fix: redemption widget - direct click on Redeem exchange

packages/react-kit/src/components/config/ConfigContext.ts, packages/react-kit/src/components/modal/components/Redeem/Confirmation/Confirmation.tsx
To be done:
- add wallet signature in the redemption message (https://github.com/bosonprotocol/widgets/issues/8)
- allow to pass additional headers to the redemption request (would be used for authentication)
=> fix: add content-type header when POST message to redeemCallbackUrl

e2e/tests/fundsEventLogs.test.ts, packages/subgraph/src/mappings/funds-handler.ts
fixes https://github.com/bosonprotocol/interface/issues/810
=> fix: fundsEventLogs shall always contain a fundsEntity reference

packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx, packages/react-kit/src/components/wallet/wallet-connection.ts, packages/react-kit/src/stories/widgets/Redemption.stories.tsx
The forcedAccount optional property allows to open the redemption widget for a specific account.
In case the wallet is already connected with another account, it forces disconnection
required for https://github.com/bosonprotocol/interface/issues/831 and https://github.com/bosonprotocol/widgets/issues/52
react-kit / storybook
=> feat: add forcedAccount property on RedemptionWidget

contracts/Dockerfile, contracts/hardhat.config.js, e2e/docker-compose.yml, e2e/meta-tx-gateway/Dockerfile, packages/common/src/types/accounts.ts
fixes #568 
on a Mac machine, the following command should NOT fail:
```
cd contracts
docker build .
```
=> fix: force amd64 platform on dockers

packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx, packages/react-kit/src/hooks/connection/useDisconnect.ts
- fix: disconnect if you connected your wallet with wagmi (metamask, etc)
- fix: reset flow, if you are in cancellation mode, and you disconnect, when you connect back you should see the cancellation page again (and not the steps overview as it was before)
=> fix: disconnect and reset flow

packages/subgraph/src/mappings/account-handler.ts, packages/subgraph/src/mappings/offer-handler.ts, packages/subgraph/tests/account-handler.test.ts, packages/subgraph/tests/funds-handler.test.ts, packages/subgraph/tests/mocks.ts, packages/subgraph/tests/offer-handler.test.ts
fixes #613 
- existing e2e:test are enough, as they are using orchestration method createSellerAndOffer, ensuring the events are dealt in the correct order
- check the warning messages on mumbai-testing env. Only the offers 540 and 541 for seller 2 should be mentionned
=> fix: do not create an offer when the seller does not exist

e2e/tests/accounts.test.ts, packages/react-kit/src/components/magicLink/MagicContext.tsx, packages/react-kit/src/hooks/magic.ts
fixes https://github.com/bosonprotocol/interface/issues/949
n/a
=> fix: excessive calls to infura provider (querying eth_chainId)

packages/react-kit/src/components/magicLink/Login.tsx, packages/react-kit/src/components/modal/components/Redeem/Confirmation/ConfirmationView.tsx, packages/react-kit/src/components/modal/components/Redeem/ContractualAgreementView/ContractualAgreementView.tsx, packages/react-kit/src/components/modal/components/Redeem/ExchangePolicy/ExchangePolicy.tsx, packages/react-kit/src/components/modal/components/Redeem/ExchangeView/ExchangeFullDescriptionView/ExchangeFullDescriptionView.tsx, packages/react-kit/src/components/modal/components/Redeem/ExchangeView/ExchangeView.tsx, packages/react-kit/src/components/modal/components/Redeem/ExchangeView/RedeemSuccess.tsx, packages/react-kit/src/components/modal/components/Redeem/ExchangeView/cancellation/CancellationView.tsx, packages/react-kit/src/components/modal/components/Redeem/ExchangeView/expireVoucher/ExpireVoucherView.tsx, packages/react-kit/src/components/modal/components/Redeem/LicenseAgreementView/LicenseAgreementView.tsx, packages/react-kit/src/components/modal/components/Redeem/MyItems/MyItems.tsx, packages/react-kit/src/components/modal/components/Redeem/RedeemForm/RedeemFormView.tsx, packages/react-kit/src/components/modal/components/Redeem/RedeemHeader.tsx, packages/react-kit/src/components/modal/components/Redeem/RedeemNonModal.tsx, packages/react-kit/src/components/modal/components/Redeem/StepsOverview/PurchaseOverviewView.tsx, packages/react-kit/src/components/modal/components/Redeem/StepsOverview/StepsOverview.tsx, packages/react-kit/src/components/modal/nonModal/Header.tsx, packages/react-kit/src/components/wallet/ConnectButton.tsx
=> fix: responsiveness header redemption widget

e2e/tests/bundle.test.ts, e2e/tests/productV1.test.ts, e2e/tests/utils.ts, packages/core-sdk/src/metadata/mixin.ts, packages/core-sdk/src/metadata/product-v1.graphql, packages/core-sdk/src/metadata/subgraph.ts, packages/core-sdk/src/subgraph.ts, packages/subgraph/schema.graphql, packages/subgraph/src/entities/metadata/bundle/index.ts, packages/subgraph/src/entities/metadata/product-v1/index.ts, packages/subgraph/src/entities/metadata/product-v1/variant.ts
coreSDK.getProductWithVariants() returns 3 fields: product, variants and bundleSets.
- product returns the productV1Product object from the subgraph regarding the passed productUUID. As before, this product can be offered through simple offers (not bundle), either as a mono-variant (only 1 offer) or multi-variant (1 different offer per variant). Now this product can be offered through bundle offers, either as mono-variant or multi-variant. 
- variants returns the variants of the given product, offered OUTSIDE of any bundle. Only one variant means a mono-variant product,s everal variants means a multi-variant one. No variant at all means the product is ONLY offered through bundles
- bundleSets lists all bundle that include the product, if any. bundleSet is mapped per bundleUuid. A set …
=> chore: rework the way to fetch the product/variants for bundle offers

packages/common/src/utils/validation.ts, packages/common/tests/utils/validation.test.ts, packages/core-sdk/src/meta-tx/handler.ts
fix: validation text error
fix: return of wait function of meta tx so it doesnt crash if txReceipt is undefined
=> fix: validation error and access to property in wait biconomy

packages/common/src/abis/Seaport.json, scripts/export-abis.ts
=> fix: export-abis script is failing since prettier dependency upgrade

packages/react-kit/src/components/modal/components/common/OfferFullDescription/DigitalProductData.tsx, packages/react-kit/src/components/modal/components/common/detail/DetailTable.tsx
=> fix: alignment digital product data to the right

packages/react-kit/src/components/ui/Grid.tsx, packages/react-kit/src/components/ui/Typography.tsx, packages/react-kit/src/components/ui/common.ts
valid props with value 0 were being ignored (like setting margin={0}), now that's fixed
=> fix: grid and typography components

packages/core-sdk/src/index.ts, packages/core-sdk/src/marketplaces/index.ts, packages/core-sdk/src/marketplaces/opensea.ts, packages/core-sdk/src/marketplaces/types.ts
- add Filtering capability on getOrder() method
- add getOrders() method to get orders for a list of tokens
=> feat: improve opensea wrapper

packages/common/src/types/configs.ts, packages/core-sdk/src/index.ts, packages/react-kit/src/components/wallet2/selector/ChainSelector.tsx, packages/react-kit/src/stories/ConnectWallet.stories.tsx
this is to allow this component to be used by fermion with a different config object type
=> refactor: make chain selector component config agnostic

e2e/docker-compose.yml, e2e/opensea-api-mock/package.json, e2e/opensea-api-mock/src/services/opensea.ts, package-lock.json, package.json, packages/core-sdk/package.json, packages/core-sdk/src/marketplaces/opensea.ts, packages/core-sdk/src/marketplaces/types.ts, packages/core-sdk/tests/marketplaces/opensea.test.ts
related to https://github.com/fermionprotocol/core-components/issues/110
Issue comes from different opensea-js versions between Boson CC and Fermion CC.
OrderSide enum type has been redefined between these 2 versions.
Boson CC upgraded to the latest opensea-js version in order to match those used in Fermion
unit test added to meet the coverage threshold
=> chore: upgrade opensea-js dep and change OrderSide enum type

packages/core-sdk/src/marketplaces/opensea.ts
temporary, generateFulfillmentData() is called with forcing the order side to be LISTING (Ask) instead of OFFER (Bid).
Even if not semantically correct, the method returns the needed data to fulfil an offer (Bid), so it works around the issue raised on the Fermion dApp: https://github.com/fermionprotocol/ui/issues/358
=> fix: hack waiting for Opensea API bug to be fixed

packages/core-sdk/src/marketplaces/mixin.ts, packages/core-sdk/src/marketplaces/opensea.ts, packages/core-sdk/src/marketplaces/types.ts
if we want to create a listing that starts in the future then we need to set the listingTime AFAIK
also change the types in the MarketplaceMixin so it returns an OpenSeaHandler if that is the case
=> feat: add listingTime and narrow down marketplace returned

packages/react-kit/src/components/form/BaseCheckbox.tsx, packages/react-kit/src/stories/form/BaseCheckbox.stories.tsx
right now if you set the text prop of a checkbox the text that appears is bold, with children it could be anything if it's set
=> feat: add children prop to checkbox

packages/subgraph/README.md
CI workflows are not started when PR #784 and PR #841  are merged
This may be the reason why 
=> chore: empty commit to force ci workflow

.github/workflows/deploy-testing-subgraph.yaml, .github/workflows/publish-alpha.yaml
=> ci: fix GITHUB_TOKEN variable name can't be used (reserved)

.github/workflows/deploy-prod-subgraph.yaml, .github/workflows/deploy-staging-subgraph.yaml
As the staging workflow is run on a release (tag), the checkout is with detached HEAD, meaning it's not possible to just make change and push them.
==> We specify the main branch as the branch where to push in
In addition, some changes done in testing / staging wrokflow are reported in the production workflow as an ancipation before it being tested
=> ci: fix staging subgraph deployment workflow

.github/workflows/deploy-prod-subgraph.yaml
=> ci: force the production subgraph deployment to be on a release tag

packages/react-kit/src/components/wallet2/selector/ChainSelector.tsx, packages/react-kit/src/components/wallet2/selector/getSupportedChainIdsFromWalletConnectSession.ts
from https://github.com/Uniswap/interface/blob/main/apps/web/src/utils/getSupportedChainIdsFromWalletConnectSession.ts
=> feat: add getSupportedChainIdsFromWalletConnectSession

packages/react-kit/src/components/ui/IpfsImage.tsx, packages/react-kit/src/components/widgets/finance/FinanceWidgetProviders.tsx, packages/react-kit/src/components/widgets/redemption/RedemptionWidgetProviders.tsx
sometimes the IpfsImage showed the loading spinner even if the image was already loaded...this is because the browser doesnt load images that are hidden behind "display: none" and there was a race condition that should be fixed now
the change is to basically show the loading and error states on top of the actual image so the img tag is never hidden by "display: none"
=> fix: ipfs image race condition

packages/common/src/configs.ts
=> chore: add urls for meta-tx-gateway on base networks

packages/subgraph/scripts/post-deploy-on-ormi.ts
=> fix: add missing environment for post subgraph deployment with Ormi

packages/react-kit/src/components/form/Select.tsx, packages/react-kit/src/components/form/types.ts, packages/react-kit/src/stories/selects/Select.stories.tsx
if the select is disabled now:
- cursor should change to not-allowed
- border and caret down indicator should not change in color when hovered
- X buttons on selected options when select isMulti should not change in style when hovered
=> style: change select styles when disabled

.gitignore, contracts/package.json
used the commit of this tag
https://github.com/bosonprotocol/boson-protocol-contracts/tree/v2.4.2-rc.2
=> chore: upgrade contracts to v2.4.2-rc.2
